name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build docker image and push to docker hub
        run: |
          cd backend
          docker build -t vanshbehal01/online_judge:backend .
          docker push vanshbehal01/online_judge:backend
